name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      GOOGLE_APPLICATION_CREDENTIALS_JSON: $HOME/firebase-service-account.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm generate

      - name: Install firebase-tools
        run: pnpm install -g firebase-tools

      - name: Create Service Account
        run: echo $FIREBASE_SERVICE_ACCOUNT > $HOME/firebase-service-account.json

      - name: Deploy
        run: firebase deploy --debug

      - name: Remove credentials file
        if: success() || failure()
        run: |
          rm $HOME/firebase-service-account.json
