name: Deploy to Firebase Hosting

on:
  workflow_dispatch:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm generate

      - name: Install firebase-tools
        run: pnpm install -g firebase-tools

      - name: Deploy
        env: # Or as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --token "$FIREBASE_TOKEN"
